services:
  - type: web
    name: multilingual-video-pipeline
    runtime: python
    repo: https://github.com/infinawaz/Multilingual-Video-Text-Annotation-and-Translation-Pipeline.git
    branch: main
    buildCommand: "./build.sh"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /api/health
    envVars:
      - key: LIBRETRANSLATE_URL
        value: https://libretranslate.com
      - key: PYTHON_VERSION
        value: "3.10.12"
